-- Verifies the Phase 2 migrations (V010-V060) against the migrated database.
-- Part A only reads. Part B tries to insert/update bad data to prove each
-- constraint blocks it; everything is rolled back at the end.
SET LINESIZE 200
SET PAGESIZE 200
SET FEEDBACK ON
COLUMN constraint_name FORMAT A26
COLUMN table_name      FORMAT A20
COLUMN index_name      FORMAT A26
COLUMN columns         FORMAT A32
COLUMN reason          FORMAT A30
COLUMN raw_amount      FORMAT A18
COLUMN full_name       FORMAT A28
COLUMN pan             FORMAT A12
COLUMN policy_no       FORMAT A16

PROMPT ######## PART A - state after migrations

PROMPT === A1. Row counts (expect 155 / 194 / 470 / 2)
SELECT (SELECT COUNT(*) FROM CUSTOMERS)           customers,
       (SELECT COUNT(*) FROM POLICIES)            policies,
       (SELECT COUNT(*) FROM PAYMENTS)            payments,
       (SELECT COUNT(*) FROM PAYMENTS_QUARANTINE) quarantined
FROM dual;

PROMPT === A2. MODE_CODE (expect H 27, M 59, Q 43, Y 64, NULL 1)
SELECT NVL(MODE_CODE, '-') mode_code, COUNT(*) n FROM POLICIES GROUP BY MODE_CODE ORDER BY 1;

PROMPT === A3. Policies with no mode (expect only 5018 SINGLE)
SELECT POLICY_ID, PREMIUM_MODE FROM POLICIES WHERE MODE_CODE IS NULL;

PROMPT === A4. PREMIUM parsed (expect 194 total, 191 parsed)
SELECT COUNT(*) total, COUNT(PREMIUM) parsed, MIN(PREMIUM) min_premium, MAX(PREMIUM) max_premium FROM POLICIES;

PROMPT === A5. Policies with no premium (expect 5014, 5015, 5016)
SELECT POLICY_ID, '[' || PREMIUM_AMOUNT || ']' raw_amount FROM POLICIES WHERE PREMIUM IS NULL ORDER BY 1;

PROMPT === A6. One sample of each premium format (expect 4200, 24000, 24000, 60000, 3200, 1500)
SELECT POLICY_ID, '[' || PREMIUM_AMOUNT || ']' raw_amount, PREMIUM
FROM POLICIES WHERE POLICY_ID IN (5002, 5006, 5028, 5037, 5041, 5004) ORDER BY 1;

PROMPT === A7. Policy numbers not in clean format (expect no rows)
SELECT POLICY_ID, POLICY_NO FROM POLICIES WHERE POLICY_NO <> UPPER(TRIM(POLICY_NO));

PROMPT === A8. Duplicate policy numbers (expect only SL-2024-000120, 2 rows)
SELECT POLICY_NO, COUNT(*) n FROM POLICIES GROUP BY POLICY_NO HAVING COUNT(*) > 1;

PROMPT === A9. Quarantine (expect 700468 DUPLICATE_CHARGE_REFUND_DUE, 700469 ORPHAN_POLICY)
SELECT PAYMENT_ID, POLICY_ID, AMOUNT, REASON FROM PAYMENTS_QUARANTINE ORDER BY 1;

PROMPT === A10. The kept half of the double charge (expect 700467 present, 700468 absent)
SELECT PAYMENT_ID, POLICY_ID, AMOUNT FROM PAYMENTS WHERE PAYMENT_ID IN (700467, 700468);

PROMPT === A11. Customers still messy (expect no rows)
SELECT CUSTOMER_ID, FULL_NAME, PAN FROM CUSTOMERS
WHERE FULL_NAME <> TRIM(FULL_NAME) OR REGEXP_LIKE(FULL_NAME, '\s{2,}')
   OR NOT REGEXP_LIKE(PAN, '^[A-Z]{5}[0-9]{4}[A-Z]$');

PROMPT === A12. Customers 1152-1155 after cleanup
SELECT CUSTOMER_ID, '[' || FULL_NAME || ']' full_name, PAN FROM CUSTOMERS WHERE CUSTOMER_ID BETWEEN 1152 AND 1155;

PROMPT === A13. Constraints (NOT VALIDATED expected only on UQ_POL_POLICY_NO, FK_POL_CUSTOMER, CK_POL_DUE_DATES)
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, VALIDATED
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('CUSTOMERS', 'POLICIES', 'PAYMENTS', 'PAYMENTS_QUARANTINE')
  AND CONSTRAINT_NAME NOT LIKE 'SYS_%'
ORDER BY TABLE_NAME, CONSTRAINT_NAME;

PROMPT === A14. Indexes
SELECT i.TABLE_NAME, i.INDEX_NAME, i.UNIQUENESS,
       LISTAGG(c.COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY c.COLUMN_POSITION) columns
FROM USER_INDEXES i
JOIN USER_IND_COLUMNS c ON c.INDEX_NAME = i.INDEX_NAME
WHERE i.TABLE_NAME IN ('CUSTOMERS', 'POLICIES', 'PAYMENTS', 'PAYMENTS_QUARANTINE')
GROUP BY i.TABLE_NAME, i.INDEX_NAME, i.UNIQUENESS
ORDER BY 1, 2;

PROMPT ######## PART B - constraints must block bad NEW data
PROMPT ######## Every statement below should FAIL with the ORA error shown (except B12)
WHENEVER SQLERROR CONTINUE

PROMPT === B1. Duplicate policy number -> expect ORA-00001 (UQ_POL_POLICY_NO)
INSERT INTO POLICIES (POLICY_ID, POLICY_NO, CUSTOMER_ID, COMMENCEMENT_DATE)
VALUES (999001, 'SL-2024-000101', 1001, SYSDATE);

PROMPT === B2. Policy for a missing customer -> expect ORA-02291 (FK_POL_CUSTOMER)
UPDATE POLICIES SET CUSTOMER_ID = 999999 WHERE POLICY_ID = 5001;

PROMPT === B3. Invalid mode code -> expect ORA-02290 (CK_POL_MODE_CODE)
UPDATE POLICIES SET MODE_CODE = 'X' WHERE POLICY_ID = 5001;

PROMPT === B4. Zero premium -> expect ORA-02290 (CK_POL_PREMIUM_POSITIVE)
UPDATE POLICIES SET PREMIUM = 0 WHERE POLICY_ID = 5001;

PROMPT === B5. First unpaid after next due on a changed row -> expect ORA-02290 (CK_POL_DUE_DATES)
UPDATE POLICIES SET FIRST_UNPAID_DUE_DATE = NEXT_DUE_DATE + 1 WHERE POLICY_ID = 5001;

PROMPT === B6. Reused idempotency key -> expect ORA-00001 (UQ_PAY_IDEM_KEY)
INSERT INTO PAYMENTS (PAYMENT_ID, POLICY_ID, AMOUNT, PAID_AT, IDEMPOTENCY_KEY, COVERS_DUE_DATE, CHANNEL)
SELECT 999001, POLICY_ID, AMOUNT, SYSTIMESTAMP, IDEMPOTENCY_KEY, COVERS_DUE_DATE + 9999, 'BRANCH'
FROM PAYMENTS WHERE PAYMENT_ID = 700001;

PROMPT === B7. Same instalment paid again with a new key -> expect ORA-00001 (UQ_PAY_POLICY_DUE)
INSERT INTO PAYMENTS (PAYMENT_ID, POLICY_ID, AMOUNT, PAID_AT, IDEMPOTENCY_KEY, COVERS_DUE_DATE, CHANNEL)
SELECT 999002, POLICY_ID, AMOUNT, SYSTIMESTAMP, 'verify-new-key-1', COVERS_DUE_DATE, 'BRANCH'
FROM PAYMENTS WHERE PAYMENT_ID = 700001;

PROMPT === B8. Payment for a missing policy -> expect ORA-02291 (FK_PAY_POLICY)
INSERT INTO PAYMENTS (PAYMENT_ID, POLICY_ID, AMOUNT, PAID_AT, IDEMPOTENCY_KEY, COVERS_DUE_DATE, CHANNEL)
VALUES (999003, 888888, 100, SYSTIMESTAMP, 'verify-new-key-2', SYSDATE, 'BRANCH');

PROMPT === B9. Negative amount -> expect ORA-02290 (CK_PAY_AMOUNT_POSITIVE)
INSERT INTO PAYMENTS (PAYMENT_ID, POLICY_ID, AMOUNT, PAID_AT, IDEMPOTENCY_KEY, COVERS_DUE_DATE, CHANNEL)
VALUES (999004, 5001, -1, SYSTIMESTAMP, 'verify-new-key-3', SYSDATE + 9999, 'BRANCH');

PROMPT === B10. Unknown channel -> expect ORA-02290 (CK_PAY_CHANNEL)
INSERT INTO PAYMENTS (PAYMENT_ID, POLICY_ID, AMOUNT, PAID_AT, IDEMPOTENCY_KEY, COVERS_DUE_DATE, CHANNEL)
VALUES (999005, 5001, 6000, SYSTIMESTAMP, 'verify-new-key-4', SYSDATE + 9999, 'CASH');

PROMPT === B11. Bad PAN -> expect ORA-02290 (CK_CUST_PAN_FORMAT)
UPDATE CUSTOMERS SET PAN = 'abcde1234f' WHERE CUSTOMER_ID = 1001;

PROMPT === B12. Normal update on a NOVALIDATE duplicate row -> expect "1 row updated" (must NOT fail,
PROMPT ===      RECORD_PAYMENT will update 5019/5020 due dates later)
UPDATE POLICIES SET NEXT_DUE_DATE = NEXT_DUE_DATE + 1 WHERE POLICY_ID = 5020;

PROMPT === B13. Lower-case copy of an existing policy number -> expect ORA-02290 (CK_POL_POLICY_NO_FORMAT, V045)
INSERT INTO POLICIES (POLICY_ID, POLICY_NO, CUSTOMER_ID, COMMENCEMENT_DATE)
VALUES (999002, 'sl-2024-000101', 1001, SYSDATE);

ROLLBACK;
PROMPT ######## All Part B changes rolled back.
EXIT
