WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET FEEDBACK ON
PROMPT V010: payment quarantine

-- Payments that cannot stay in PAYMENTS (they break a constraint) are moved
-- here with a reason. Financial rows are never deleted.
CREATE TABLE PAYMENTS_QUARANTINE (
  PAYMENT_ID       NUMBER        NOT NULL,
  POLICY_ID        NUMBER,
  AMOUNT           NUMBER(12,2),
  PAID_AT          TIMESTAMP,
  IDEMPOTENCY_KEY  VARCHAR2(64),
  COVERS_DUE_DATE  DATE,
  CHANNEL          VARCHAR2(20),
  CREATED_AT       TIMESTAMP,
  REASON           VARCHAR2(60)  NOT NULL,
  NOTE             VARCHAR2(400),
  QUARANTINED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PAYMENTS_QUARANTINE PRIMARY KEY (PAYMENT_ID)
);

COMMIT;
EXIT