WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET FEEDBACK ON
PROMPT V030: parse free-text PREMIUM_AMOUNT into PREMIUM NUMBER(12,2)

ALTER TABLE POLICIES ADD (PREMIUM NUMBER(12,2));


UPDATE POLICIES
SET PREMIUM = TO_NUMBER(
      REPLACE(REPLACE(REGEXP_REPLACE(UPPER(TRIM(PREMIUM_AMOUNT)), '^(RS\.?|INR)\s*', ''), ',', ''), ' ', '')
      DEFAULT NULL ON CONVERSION ERROR);


UPDATE POLICIES SET PREMIUM = NULL WHERE PREMIUM <= 0;
ALTER TABLE POLICIES ADD CONSTRAINT CK_POL_PREMIUM_POSITIVE CHECK (PREMIUM > 0);

COMMIT;
EXIT