WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET FEEDBACK ON
PROMPT V050: payment quarantine, keys and checks

-- Payments that cannot stay in PAYMENTS are MOVED here with a reason.
-- Financial rows are never just deleted.
CREATE TABLE PAYMENTS_QUARANTINE (
  PAYMENT_ID       NUMBER        NOT NULL,
  POLICY_ID        NUMBER,
  AMOUNT           NUMBER(12,2),
  PAID_AT          TIMESTAMP,
  IDEMPOTENCY_KEY  VARCHAR2(64),
  COVERS_DUE_DATE  DATE,
  CHANNEL          VARCHAR2(20),
  CREATED_AT       TIMESTAMP,
  REASON           VARCHAR2(40)  NOT NULL,
  QUARANTINED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PAYMENTS_QUARANTINE PRIMARY KEY (PAYMENT_ID)
);

-- 1. Payment for a policy that does not exist (700469 -> policy 888888).
--    FK failed with ORA-02298. Unexplained money: quarantine for finance.
INSERT INTO PAYMENTS_QUARANTINE
  (PAYMENT_ID, POLICY_ID, AMOUNT, PAID_AT, IDEMPOTENCY_KEY, COVERS_DUE_DATE, CHANNEL, CREATED_AT, REASON)
SELECT PAYMENT_ID, POLICY_ID, AMOUNT, PAID_AT, IDEMPOTENCY_KEY, COVERS_DUE_DATE, CHANNEL, CREATED_AT, 'ORPHAN_POLICY'
FROM PAYMENTS y
WHERE NOT EXISTS (SELECT 1 FROM POLICIES p WHERE p.POLICY_ID = y.POLICY_ID);

DELETE FROM PAYMENTS y
WHERE NOT EXISTS (SELECT 1 FROM POLICIES p WHERE p.POLICY_ID = y.POLICY_ID);

-- 2. Same idempotency key charged twice (BR-RETRY-7C41E9AA: 700467 and 700468,
--    3 seconds apart, policy 5034). Unique key failed with ORA-02299.
--    The first is the real payment; every later one is a double charge to refund.
INSERT INTO PAYMENTS_QUARANTINE
  (PAYMENT_ID, POLICY_ID, AMOUNT, PAID_AT, IDEMPOTENCY_KEY, COVERS_DUE_DATE, CHANNEL, CREATED_AT, REASON)
SELECT PAYMENT_ID, POLICY_ID, AMOUNT, PAID_AT, IDEMPOTENCY_KEY, COVERS_DUE_DATE, CHANNEL, CREATED_AT, 'DUPLICATE_CHARGE_REFUND_DUE'
FROM (SELECT y.*, ROW_NUMBER() OVER (PARTITION BY IDEMPOTENCY_KEY ORDER BY PAID_AT, PAYMENT_ID) AS rn
      FROM PAYMENTS y)
WHERE rn > 1;

DELETE FROM PAYMENTS
WHERE PAYMENT_ID IN (SELECT PAYMENT_ID FROM PAYMENTS_QUARANTINE WHERE REASON = 'DUPLICATE_CHARGE_REFUND_DUE');

-- 3. Constraints - all fully VALIDATED now.
ALTER TABLE PAYMENTS MODIFY (POLICY_ID NOT NULL, AMOUNT NOT NULL, PAID_AT NOT NULL,
                             IDEMPOTENCY_KEY NOT NULL, COVERS_DUE_DATE NOT NULL, CHANNEL NOT NULL);

ALTER TABLE PAYMENTS ADD CONSTRAINT FK_PAY_POLICY FOREIGN KEY (POLICY_ID) REFERENCES POLICIES (POLICY_ID);

-- R8: the same key can never create a second payment.
-- Its index serves: the key lookup inside RECORD_PAYMENT.
ALTER TABLE PAYMENTS ADD CONSTRAINT UQ_PAY_IDEM_KEY UNIQUE (IDEMPOTENCY_KEY);

-- R8: one payment per instalment, even with two different keys.
-- Its index (starts with POLICY_ID) also serves: payment history
-- WHERE POLICY_ID = :id, and indexes the foreign key above.
ALTER TABLE PAYMENTS ADD CONSTRAINT UQ_PAY_POLICY_DUE UNIQUE (POLICY_ID, COVERS_DUE_DATE);

ALTER TABLE PAYMENTS ADD CONSTRAINT CK_PAY_AMOUNT_POSITIVE CHECK (AMOUNT > 0);
ALTER TABLE PAYMENTS ADD CONSTRAINT CK_PAY_CHANNEL CHECK (CHANNEL IN ('BRANCH', 'ONLINE', 'AGENT', 'AUTO-DEBIT'));

COMMIT;
EXIT